# Generated by Django 4.1.7 on 2023-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_backend_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
